### ISSUE TITLE
Admin changes checklist

### ISSUE THREAD

**Issue by BomLe** [hackforla/adopt-civic-art#24]
Adoptions
- [ ] Ability to see multiple adopters at a glance (may be a dashboard feature)

Artworks 
- [x] Change Creation Date field from YYYY-MM-DD to YYYY
- [x] Ability to toggle display from Creation Date to Date Description (but always sort/filter by Creation Date)
- [x] Add picklist for Medium field
- [x] Add picklist for Artwork Type field
- [x] Delete Author field from artwork images section
- [x] Make License field for artwork images internal-facing only

**Comment by xtine** [comment]
@LACAC-YLee: What the options for the Medium and Artwork Type picklist? I need to define the choices in the database model.

**Comment by BomLe** [comment]
@xtine: 
Medium
* acrylic paint
* actor
* alloy steel
* bronze
* ceramic glaze
* charcoal
* concrete
* copper
* Cor-Ten steel
* crayon
* digital moving image format
* enamel paint
* fiberglass
* Fome-Cor
* found object
* galvanized steel
* glass
* granite
* graphite
* grass
* house paint
* industrial paint
* ink
* latex paint
* lead
* marble
* metal
* oil paint
* paint and varnish
* paper
* pastel
* performance art
* plant material
* plastic
* Plexiglas
* polyester (fiber)
* porcelain
* rammed earth
* resin
* rock
* stainless steel
* stone
* terra-cotta
* textile
* tree
* video monitor
* watercolor
* wood

**Comment by BomLe** [comment]
@xtine:
Artwork Type

* banner
* book
* catalog
* collage
* computer-aided design
* cyanotype
* diagram
* digital image
* ephemera
* etching
* event
* fence
* floor
* floor plan
* fountain
* garden
* glass
* installation
* kinetic sculpture
* leaflet
* lighting fixture
* map
* model
* monument
* mural
* packaging
* paint scheme
* painting
* periodical
* photograph
* picture
* plaque
* playground equipment
* poster
* print
* reproduction
* scroll
* sculpture
* tapestry
* textile art
* tile
* video art

**Comment by xtine** [comment]
@LACAC-YLee I'm getting to these changes now. For Medium or Artwork Type, would you only choose one from the list or potentially multiple options from the picklists? And would you like these editable in the admin just like how damage descriptions are now?

**Comment by xtine** [comment]
I updated creation dates to YYYY and a "show date description" toggle on admin for artworks, and live on dev server now.

**Comment by BomLe** [comment]
@xtine 
* Medium would be multiple options from the list
* Artwork Type would be one option from the list
* Both should be editable in admin, just like Damage Description

Awesome news about date! I'll try it out later today.

**Comment by xtine** [comment]
I just added Artwork Medium List and Artwork Type Lists, you should be able to control them in the admin now.

**Comment by BomLe** [comment]
Just completed adding terms for Medium and Artwork Type to the dev site!

**Comment by xtine** [comment]
The main admin changes have been done, can make a new issue for dashboard needs.
