### ISSUE TITLE
Google Analytics event tracking

### ISSUE THREAD

**Issue by xtine** [hackforla/adopt-civic-art#34]
To best track metrics and site usage, we should have event tracking tied to Google Analytics to best analyze our data.
- [ ] Identify types of events to track (user signup, adoptions, checkins, etc)
- [ ] Set up Google Analytics account
- [ ] Set up GA events
